type Localized = { en: string; ar: string }
const l = (en: string, ar: string): Localized => ({ en, ar })
export const BUSINESS = {
  name: l('Eldokan', 'الدكان'),
  address: l('32 Saab Saleh Street, Ain Shams, Egypt', '32 شارع صعب صالح، عين شمس، مصر'),
  email: 'wecare@eldokan.com', phone: '+201006806022',
}
export const MERCHANT_PROPOSAL = { commissionPercent: 10, settlement: 'weekly', version: 'draft-1' } as const
export const CONSUMER_RIGHTS_URL = 'https://cpa.gov.eg/ar-eg/بيانات-اعلامية/ArtMID/654/ArticleID/6790'
export type PolicySection = { id: string; title: Localized; paragraphs: Localized[] }
export type Policy = { slug: string; title: Localized; summary: Localized; audience: 'all' | 'buyer' | 'seller'; sections: PolicySection[] }
const section = (id: string, title: Localized, ...paragraphs: Localized[]): PolicySection => ({ id, title, paragraphs })

/** Review drafts. Commercial values here do not configure WooCommerce or payouts. */
export const POLICIES: Policy[] = [
  { slug: 'terms', audience: 'all', title: l('Terms of use', 'شروط استخدام الموقع'), summary: l('Accounts, acceptable use, content and disputes.', 'الحسابات والاستخدام المقبول والمحتوى والشكاوى.'), sections: [
    section('scope', l('Scope & identity', 'نطاق الخدمة والهوية'), l('Eldokan is the store name supplied by the owner. The business address is shown on this page. The legal entity, registration and tax details must be completed before these drafts become effective.', 'الدكان هو اسم المتجر المقدم من صاحب المشروع، وعنوانه موضح في الصفحة. يلزم استكمال هوية الكيان القانوني وبيانات التسجيل والضرائب قبل سريان هذه المسودات.')),
    section('accounts', l('Accounts & account security', 'الحسابات وأمانها'), l('Provide accurate contact details, keep access credentials private and report suspected misuse. Use an account you are authorized to operate. Do not share another customer’s order access.', 'اكتب بيانات تواصل صحيحة، وحافظ على سرية بيانات الدخول، وبلغ عن أي استخدام مشبوه. استخدم حسابًا مخولًا لك، ولا تشارك وسيلة الوصول لطلب عميل آخر.')),
    section('conduct', l('Acceptable use', 'الاستخدام المقبول'), l('Do not impersonate another person, publish unlawful or abusive content, manipulate reviews, send spam, scrape private data or interfere with the service. Any restriction should be proportionate and allow support review.', 'ممنوع انتحال الهوية أو نشر محتوى مخالف أو مسيء أو التلاعب بالتقييمات أو إرسال رسائل مزعجة أو جمع بيانات خاصة أو تعطيل الخدمة. يجب أن تكون القيود متناسبة مع إمكانية مراجعتها عبر الدعم.')),
    section('content', l('Product content & intellectual property', 'محتوى المنتجات والملكية الفكرية'), l('Sellers must have permission to use their product images, descriptions and marks. Customer content must reflect genuine experience. Product comparison uses available information and does not certify that two listings are identical.', 'البائع مسؤول عن امتلاك حق استخدام صور ووصف وعلامات منتجاته. محتوى العميل يجب أن يعبر عن تجربة حقيقية. المقارنة تستخدم البيانات المتاحة ولا تضمن أن عرضين لنفس المنتج متطابقان.')),
    section('changes', l('Changes & availability', 'التعديلات وتوفر الخدمة'), l('Publish the effective version and date of approved changes and retain the version applicable to each transaction. Service interruptions do not erase customer rights or a saved order. An uncertain payment must be followed up on the same order.', 'تُنشر نسخة وتاريخ سريان التعديلات المعتمدة، وتُحفظ النسخة المطبقة على كل معاملة. تعطل الخدمة لا يلغي حقوق العميل أو طلبه المحفوظ، ويُتابع الدفع غير المؤكد على نفس الطلب.')),
    section('disputes', l('Complaints & applicable rights', 'الشكاوى والحقوق المطبقة'), l('Contact support with the order reference and relevant evidence. Nothing in these drafts removes mandatory consumer rights or access to competent authorities. The operator must approve the final dispute and jurisdiction wording.', 'تواصل مع الدعم برقم الطلب والمستندات ذات الصلة. لا تلغي هذه المسودات حقوق المستهلك الإلزامية أو اللجوء للجهات المختصة. يلزم اعتماد صياغة النزاعات والاختصاص النهائي من مشغل المتجر.')),
  ] },
  { slug: 'buyer-terms', audience: 'buyer', title: l('Customer purchase terms', 'شروط الشراء للعملاء'), summary: l('Prices, orders, payment, delivery and customer responsibilities.', 'الأسعار والطلبات والدفع والتسليم ومسؤوليات العميل.'), sections: [
    section('information', l('Review before ordering', 'المراجعة قبل الطلب'), l('Review the seller, product description, condition, options, warranty and quantity. For products with variants, select the actual size, color or specification before placing an order. Missing information is not a promised feature.', 'راجع البائع ووصف المنتج وحالته واختياراته وضمانه وكميته. اختار المقاس أو اللون أو المواصفة الفعلية للمنتج قبل الطلب. المعلومة غير المذكورة ليست ميزة مضمونة.')),
    section('pricing', l('Prices & totals', 'الأسعار والإجمالي'), l('The server-confirmed checkout quote controls the transaction price. Review shipping, tax, discounts and fees in the final total. A browsing price or comparison is not a shipping quote; changed amounts require a new customer review.', 'عرض checkout المعتمد من السيرفر هو مرجع سعر المعاملة. راجع الشحن والضرائب والخصومات والرسوم ضمن الإجمالي النهائي. سعر التصفح أو المقارنة ليس عرض شحن؛ تغير المبلغ يحتاج مراجعة جديدة من العميل.')),
    section('payment', l('Payment & confirmation', 'الدفع والتأكيد'), l('Only eligible payment methods advertised at checkout may be used. For hosted payment, use the secure provider page. Returning to the store is not proof of payment; confirmation comes from the authoritative order status. Do not start a second order to recover payment.', 'تُستخدم وسائل الدفع المؤهلة الظاهرة في checkout. في الدفع الإلكتروني استخدم صفحة مزود الدفع الآمنة. الرجوع للموقع ليس إثبات دفع؛ التأكيد من حالة الطلب المعتمدة. لا تنشئ طلبًا ثانيًا لاستعادة الدفع.')),
    section('address', l('Address & receiving orders', 'العنوان واستلام الطلب'), l('Provide a complete delivery address and reachable phone. Delivery options depend on the cart and address. Report missing, damaged or incorrect items promptly with the order reference; inspection does not waive applicable statutory rights.', 'اكتب عنوان توصيل كامل ورقم هاتف يمكن الوصول إليه. خيارات الشحن تعتمد على السلة والعنوان. بلغ عن المنتجات الناقصة أو التالفة أو غير المطابقة برقم الطلب؛ الفحص لا يسقط الحقوق القانونية المطبقة.')),
    section('cancellation', l('Cancellation & refunds', 'الإلغاء والاسترداد'), l('Request cancellation through support before fulfillment where possible. A request is not confirmed until the order service confirms the outcome. Dispatched orders follow the applicable return process. Refunds must not be represented as complete until confirmed.', 'اطلب الإلغاء عبر الدعم قبل التنفيذ متى أمكن. تقديم الطلب لا يعني تأكيده حتى تؤكد خدمة الطلبات النتيجة. الطلبات المشحونة تخضع لإجراءات الإرجاع المطبقة، ولا يُعرض الاسترداد كمكتمل قبل تأكيده.')),
    section('reviews', l('Reviews & guest access', 'التقييمات ووصول الضيف'), l('Temporary reviews in this version are stored only in the browser and are not public or verified purchases. Guest order recovery requires the original browser’s saved access; email or phone does not grant access to another order.', 'التقييمات المؤقتة في هذه النسخة محفوظة في المتصفح فقط وليست منشورة أو مشتريات موثقة. استعادة طلب الضيف تحتاج الوصول المحفوظ في المتصفح الأصلي؛ البريد أو الهاتف لا يتيحان وصولًا لطلب آخر.')),
  ] },
  { slug: 'seller-terms', audience: 'seller', title: l('Seller & merchant terms', 'شروط البائعين والتجار'), summary: l('Onboarding, listings, fulfillment, commissions and settlement.', 'التسجيل وعرض المنتجات والتنفيذ والعمولات والتسوية.'), sections: [
    section('onboarding', l('Eligibility & verification', 'الأهلية والتحقق'), l('The proposed onboarding process requires accurate business and contact information, authorized account access, bank details and the registration or tax documents required for the seller’s activity. The operator must define the final verification requirements.', 'التسجيل المقترح يتطلب بيانات نشاط وتواصل صحيحة، وصلاحية استخدام الحساب، وبيانات التحويل، ومستندات التسجيل أو الضرائب اللازمة لنشاط البائع. يحدد مشغل المتجر متطلبات التحقق النهائية.')),
    section('listings', l('Listing quality & stock', 'جودة العروض والمخزون'), l('Use accurate specifications, photographs, condition, prices, warranty and availability. Do not list counterfeit or prohibited goods or claim unverified certifications. Keep stock and variant choices current; do not substitute a different item without the customer’s agreement.', 'استخدم مواصفات وصور وحالة وأسعار وضمان وتوفر صحيحة. لا تعرض سلعًا مقلدة أو محظورة ولا تدّعي اعتمادًا غير موثق. حدّث المخزون والاختيارات، ولا تستبدل المنتج بآخر دون موافقة العميل.')),
    section('fulfillment', l('Order fulfillment', 'تنفيذ الطلبات'), l('Confirm availability, package goods appropriately and use the approved handover process. Fulfillment status and tracking must describe actual events. Delivery time commitments and escalation rules must be agreed before seller activation.', 'أكد التوفر وغلف المنتجات بشكل مناسب واتبع إجراءات التسليم المعتمدة. حالة التنفيذ والتتبع تعبر عن أحداث فعلية. تُتفق مدد تنفيذ الطلبات وآلية التصعيد قبل تفعيل البائع.')),
    section('commission', l('Proposed commission: 10%', 'العمولة المقترحة: ١٠٪'), l('Proposal only: 10% of the net goods value after discounts and returned lines, excluding separately itemized shipping and tax. The agreed rate, fee base, tax treatment and any additional charges must be configured in the seller agreement and backend before applying them.', 'اقتراح فقط: ١٠٪ من صافي قيمة السلع بعد الخصومات والمنتجات المرتجعة، دون الشحن والضرائب الموضحة كبنود مستقلة. يجب ضبط النسبة وأساس احتسابها والمعالجة الضريبية وأي رسوم إضافية في اتفاق البائع والسيرفر قبل تطبيقها.')),
    section('settlement', l('Proposed weekly settlement', 'التسوية الأسبوعية المقترحة'), l('Proposal only: a weekly statement and transfer for eligible collected orders after delivery and expiry of the applicable return period. Show commission, refunds, documented adjustments and the net balance. A collection or payout is never inferred from a frontend order label.', 'اقتراح فقط: كشف وتسوية أسبوعية للطلبات المحصلة والمؤهلة بعد التسليم وانتهاء مدة الإرجاع المطبقة. تُعرض العمولة والاستردادات والتعديلات الموثقة وصافي الرصيد. لا يُستنتج التحصيل أو التحويل من وصف حالة الطلب في الواجهة.')),
    section('returns', l('Returns & customer support', 'الإرجاع وخدمة العميل'), l('Cooperate with applicable consumer rights, product defect investigation and supported returns. Responsibility for reverse shipping and other costs must follow the law and the approved agreement; do not impose arbitrary penalties or deduct unsupported amounts.', 'التزم بحقوق المستهلك المطبقة وتعاون في فحص العيوب والإرجاع. تحدد مسؤولية شحن المرتجع والتكاليف طبقًا للقانون والاتفاق المعتمد؛ لا تفرض جزاءات عشوائية ولا تخصم مبالغ غير موثقة.')),
    section('data', l('Customer data & permissions', 'بيانات العملاء والصلاحيات'), l('Use customer details only to fulfill the authorized order or support request. Do not export them for unrelated marketing. Protect credentials, restrict staff access and report suspected disclosure through the agreed incident process.', 'استخدم بيانات العميل لتنفيذ الطلب أو طلب الدعم المصرح به فقط. لا تصدرها لتسويق غير مرتبط. احمِ بيانات الدخول وحدد صلاحيات العاملين وبلغ عن الاشتباه في تسريب وفق الإجراءات المتفق عليها.')),
    section('suspension', l('Restrictions, appeals & closing an account', 'القيود والتظلم وإغلاق الحساب'), l('The final agreement should define evidence-based restriction reasons, notice, appeal, settlement of outstanding orders and funds, and document retention. Closing a seller account does not erase customer obligations or justified financial claims.', 'يحدد الاتفاق النهائي أسباب القيود المدعومة بأدلة والإخطار والتظلم وتسوية الطلبات والأموال القائمة وحفظ المستندات. إغلاق حساب البائع لا يلغي التزاماته تجاه العملاء أو المطالبات المالية المستحقة.')),
  ] },
  { slug: 'privacy', audience: 'all', title: l('Privacy notice', 'إشعار الخصوصية'), summary: l('Collected data, purposes, recipients and privacy requests.', 'البيانات المستخدمة وأغراضها والجهات المتلقية وطلبات الخصوصية.'), sections: [
    section('controller', l('Operator & contact', 'المشغل والتواصل'), l('Contact Eldokan at the listed business address and support email. The legal data-controller identity, privacy contact and applicable registration details must be supplied by the operator before this notice is finalized.', 'تواصل مع الدكان على عنوان النشاط والبريد الموضحين. يلزم استكمال هوية المتحكم القانونية ومسؤول التواصل للخصوصية وبيانات التسجيل المطبقة من مشغل المتجر قبل اعتماد الإشعار.')),
    section('data', l('Data used in the current storefront', 'البيانات في الواجهة الحالية'), l('Forms use account names, email and an optional account phone; delivery addresses have their own contact details. Orders, cart ownership and recovery access are handled through the customer service. This browser also stores local reviews, comparison choices and recently viewed products.', 'تستخدم النماذج اسم الحساب والبريد وهاتفًا اختياريًا للحساب، ولعنوان التوصيل بيانات تواصل مستقلة. الطلبات وملكية السلة والوصول للاستعادة تتعامل معها خدمة العملاء البرمجية. ويحفظ المتصفح تقييمات محلية واختيارات المقارنة والمنتجات المشاهدة.')),
    section('purposes', l('Purposes & permissions', 'الأغراض والأذونات'), l('The proposed purposes are account operation, processing orders, delivery, payment reconciliation, support and service security. Marketing and optional tracking require a separate documented assessment and permissions where applicable; do not treat checkout as consent to unrelated marketing.', 'الأغراض المقترحة هي تشغيل الحساب وتنفيذ الطلب والتوصيل ومطابقة الدفع والدعم وأمان الخدمة. التسويق والتتبع الاختياري يحتاجان تقييمًا وأذونات مستقلة بحسب الحالة؛ لا تعتبر إتمام الشراء موافقة على تسويق غير مرتبط.')),
    section('recipients', l('Recipients & service providers', 'الجهات المتلقية ومزودو الخدمة'), l('Relevant order information may be needed by the fulfilling seller, payment provider and delivery provider when those services are used. The operator must identify actual providers, hosting locations, safeguards and any international data transfers in the approved notice.', 'قد يحتاج البائع المنفذ ومزود الدفع والشحن بيانات الطلب ذات الصلة عند استخدام خدماتهم. يحدد المشغل الجهات الفعلية ومواقع الاستضافة والضمانات وأي نقل دولي للبيانات في الإشعار المعتمد.')),
    section('retention', l('Retention & privacy requests', 'الاحتفاظ وطلبات الخصوصية'), l('A documented retention schedule and secure deletion process must be approved for account, order, payment and support records. Customers can contact support to request access, correction or deletion subject to applicable rights and record obligations. No automatic backend deletion feature is claimed here.', 'يجب اعتماد مدد موثقة للاحتفاظ وحذف آمن لسجلات الحساب والطلب والدفع والدعم. يمكن التواصل مع الدعم لطلب الوصول أو التصحيح أو الحذف وفق الحقوق والالتزامات المطبقة. لا تدعي هذه الصفحة وجود حذف تلقائي من السيرفر.')),
    section('security', l('Security & payment information', 'الأمان وبيانات الدفع'), l('Hosted payment is entered on the provider page. The storefront must not ask customers to send card details or passwords in comments or support messages. The operator must verify logging, access control, incident handling and storage safeguards before launch.', 'يُدخل الدفع الإلكتروني في صفحة المزود. لا تطلب الواجهة بيانات البطاقة أو كلمات المرور داخل التعليقات أو رسائل الدعم. يراجع المشغل التسجيل والصلاحيات والتعامل مع الحوادث وضمانات التخزين قبل الإطلاق.')),
  ] },
  { slug: 'cookies', audience: 'all', title: l('Cookies & browser storage', 'الكوكيز وتخزين المتصفح'), summary: l('Preferences, session ownership and local shopping features.', 'التفضيلات وملكية الجلسة وخصائص التسوق المحلية.'), sections: [
    section('preferences', l('Language & appearance', 'اللغة والمظهر'), l('eldokan_locale and eldokan_theme store your language and appearance preferences. The current code sets these for up to one year. You can change them using the header controls or remove them in your browser.', 'تحفظ eldokan_locale وeldokan_theme تفضيلات اللغة والمظهر، ويحدد الكود الحالي مدة تصل لسنة. يمكنك تغييرهما من أعلى الموقع أو مسحهما من المتصفح.')),
    section('session', l('Cart, account & order recovery', 'السلة والحساب واستعادة الطلب'), l('Session cookies support cart ownership and account access. eldokan_order_recovery is an HttpOnly cookie used for recovering the saved checkout and guest order, currently with a one-day lifetime. Removing necessary cookies may prevent recovery of an unfinished purchase.', 'تدعم كوكيز الجلسة ملكية السلة والوصول للحساب. eldokan_order_recovery كوكي HttpOnly لاستعادة محاولة الشراء وطلب الضيف المحفوظ، ومدته الحالية يوم. حذف الكوكيز الضرورية قد يمنع استعادة شراء غير مكتمل.')),
    section('local', l('Local storage', 'التخزين المحلي'), l('Comparison IDs, recently viewed product snapshots and temporary reviews are stored in this browser until cleared. Local reviews are not shared with other customers. Clear these only after checking any saved order and keeping records you need.', 'تُحفظ أرقام منتجات المقارنة وبيانات المنتجات المشاهدة والتقييمات المؤقتة في المتصفح حتى مسحها. التعليقات المحلية غير مشتركة مع العملاء الآخرين. راجع الطلب المحفوظ واحتفظ بما تحتاجه قبل مسح بيانات المتصفح.')),
    section('selection', l('Selection journey', 'رحلة الاختيار'), l('Your department, budget, intended use, keywords and specification choices may be saved in sessionStorage in the same browser tab for up to 24 hours. Clear saved choices in the journey to remove them. Product results and prices are requested again rather than stored as a purchase guarantee.', 'يمكن حفظ القسم والميزانية والاستخدام وكلمات البحث والمواصفات المختارة في sessionStorage داخل نفس تبويب المتصفح لمدة تصل إلى 24 ساعة. يمكنك حذفها من رحلة الاختيار. تُطلب المنتجات والأسعار مجددًا ولا تُحفظ كضمان للشراء.')),
    section('optional', l('Optional tracking', 'التتبع الاختياري'), l('Any analytics or advertising cookies introduced by hosting or plugins must be inventoried separately, with their providers, purposes, lifetimes and applicable consent controls. This page does not assume that tracking is absent on the WordPress backend.', 'تحتاج كوكيز التحليلات أو الإعلانات المضافة من الاستضافة أو الإضافات إلى حصر مستقل للجهات والأغراض والمدد والتحكم في الموافقة عند اللزوم. لا تفترض الصفحة غياب التتبع من WordPress.')),
  ] },
  { slug: 'shipping', audience: 'buyer', title: l('Shipping & delivery', 'الشحن والتوصيل'), summary: l('Service areas, costs, estimates and delivery issues.', 'مناطق الخدمة والتكلفة والتقديرات ومشاكل التسليم.'), sections: [
    section('coverage', l('Coverage & shipping costs', 'التغطية وتكلفة الشحن'), l('Available delivery methods and costs are calculated for the full cart and the entered Egyptian address. A governorate in the address list does not by itself guarantee shipping coverage. The checkout total must include the selected method’s actual cost.', 'تُحسب طرق التوصيل وتكلفتها للسلة الكاملة والعنوان المصري المدخل. وجود محافظة في قائمة العنوان لا يضمن وحده تغطية الشحن. يجب أن يتضمن إجمالي checkout تكلفة الطريقة المختارة الفعلية.')),
    section('times', l('Delivery estimates', 'تقديرات التوصيل'), l('Product delivery labels are estimates, subject to the address, seller and shipping availability. The operator must approve actual dispatch and delivery service levels. This draft does not promise a universal number of delivery days.', 'وصف التوصيل على المنتج تقديري ويعتمد على العنوان والبائع وتوفر الشحن. يعتمد المشغل مدد التنفيذ والتسليم الفعلية. لا تعد هذه المسودة بعدد أيام موحد لكل الطلبات.')),
    section('carrier', l('Carrier & tracking', 'شركة الشحن والتتبع'), l('Bosta is the intended delivery provider according to the owner. Actual shipment creation and tracking require the server integration; they are not implemented merely by publishing this page. Only confirmed shipment events should appear to customers.', 'Bosta هي شركة الشحن المستهدفة حسب صاحب المشروع. إنشاء الشحنة وتتبعها يحتاجان ربط السيرفر؛ نشر هذه الصفحة لا ينفذ الربط. تظهر للعميل أحداث الشحن المؤكدة فقط.')),
    section('issues', l('Failed delivery or damaged parcels', 'تعذر التسليم أو تلف الشحنة'), l('Contact support with the order reference if the carrier cannot reach you or the parcel is missing, damaged or incorrect. Any redelivery costs and responsibility must be explained according to the approved policy and applicable rights.', 'تواصل مع الدعم برقم الطلب إذا تعذر الوصول إليك أو كانت الشحنة مفقودة أو تالفة أو غير مطابقة. تُوضح تكاليف إعادة التسليم والمسؤولية طبقًا للسياسة المعتمدة والحقوق المطبقة.')),
  ] },
  { slug: 'returns', audience: 'buyer', title: l('Returns & refunds', 'الإرجاع والاسترداد'), summary: l('Applicable consumer rights and how to request help.', 'حقوق المستهلك المطبقة وطريقة طلب المساعدة.'), sections: [
    section('rights', l('Consumer rights in Egypt', 'حقوق المستهلك في مصر'), l('The Egyptian Consumer Protection Agency describes a 14-day return or exchange right, subject to statutory exceptions, and a 30-day window for defective goods. Consult its guidance for eligibility; this draft does not narrow those rights.', 'يوضح جهاز حماية المستهلك حق الإرجاع أو الاستبدال خلال ١٤ يومًا مع استثناءات قانونية، ومدة ٣٠ يومًا للسلع المعيبة. راجع إرشاداته للحالات المستحقة؛ هذه المسودة لا تقلص الحقوق.')),
    section('request', l('Requesting a return', 'طلب الإرجاع'), l('Send support your order reference, the affected item and the reason. Keep reasonable evidence of the condition and any purchase record. Support must explain the next step and applicable conditions without requiring unnecessary private data.', 'ابعت للدعم رقم الطلب والمنتج وسبب الطلب، واحتفظ بما يوضح حالته وسجل الشراء. يوضح الدعم الخطوة التالية والشروط المطبقة دون طلب بيانات خاصة غير ضرورية.')),
    section('refund', l('Collection, inspection & refund', 'الاستلام والفحص والاسترداد'), l('The approved process must specify return collection, inspection, responsible costs and the refund method and status. It must respect mandatory rights and applicable deadlines. A submitted request or frontend receipt does not confirm that money has been refunded.', 'يحدد المسار المعتمد استلام المرتجع وفحصه ومسؤولية التكاليف ووسيلة الاسترداد وحالته، مع احترام الحقوق والمدد الإلزامية. تقديم طلب أو عرض ملخص في الواجهة لا يؤكد رد الأموال.')),
    section('exceptions', l('Exceptions & warranty', 'الاستثناءات والضمان'), l('Apply only the relevant legal exceptions and approved product-specific conditions. Do not use a blanket exclusion for all discounted items. Warranty information must identify the actual provider and scope; missing warranty data is not an extended warranty promise.', 'تُطبق الاستثناءات القانونية ذات الصلة وشروط المنتج المعتمدة فقط. لا تستبعد كل المنتجات المخفضة بشكل عام. يحدد الضمان مقدمه ونطاقه الفعلي، وعدم ذكر بياناته لا يعني ضمانًا ممتدًا.')),
  ] },
  { slug: 'prohibited-products', audience: 'seller', title: l('Restricted products & listing standards', 'المنتجات المحظورة ومعايير العرض'), summary: l('Authenticity, regulated goods and prohibited content.', 'الأصالة والسلع المنظمة والمحتوى غير المسموح.'), sections: [
    section('prohibited', l('Prohibited goods', 'السلع غير المسموح بها'), l('Do not list illegal, stolen, counterfeit or unsafe products, prohibited weapons or illicit drugs, or content that facilitates fraud. Category-specific restrictions must be reviewed for the actual business activity and shipping rules.', 'ممنوع عرض منتجات غير قانونية أو مسروقة أو مقلدة أو غير آمنة، أو أسلحة محظورة أو مخدرات غير مشروعة، أو محتوى يسهل الاحتيال. تُراجع قيود الفئات وفق النشاط الفعلي وقواعد الشحن.')),
    section('regulated', l('Regulated products', 'المنتجات المنظمة'), l('Health, cosmetic, food and other regulated categories require any applicable approvals, labels and seller permissions. Do not advertise unsupported treatment claims or conceal expiry dates, hazards or usage restrictions.', 'الفئات الصحية والتجميلية والغذائية وغيرها من الفئات المنظمة تحتاج الموافقات والملصقات وأذونات البائع المطبقة. لا تعلن ادعاءات علاجية غير مدعومة ولا تخفِ الصلاحية أو المخاطر أو قيود الاستخدام.')),
    section('accuracy', l('Images, attributes & moderation', 'الصور والمواصفات والمراجعة'), l('Use accurate images and variant descriptions, disclose the item condition and identify warranty terms. The final policy must describe reporting, evidence review, correction, removal and seller appeal, rather than claiming automated moderation that is not connected.', 'استخدم صورًا وأوصاف اختيارات دقيقة ووضح حالة المنتج وشروط ضمانه. توضح السياسة النهائية البلاغات وفحص الأدلة والتصحيح والحذف وتظلم البائع، بدل ادعاء مراجعة آلية غير مربوطة.')),
  ] },
]

export function getPolicy(slug: string) { return POLICIES.find((policy) => policy.slug === slug) }
